namespace core.services;

using core.profanity;
using vein.project.shards;

public class PackageValidator
{
    private const long MaxAllowedIconLengthForUploading = 1024 * 1024; // 1 MB
    private const long MaxAllowedContentForUploading = 1024 * 1024 * 300; // 300 MB
    private static Profanity _censor = new ("./content");

    private static readonly List<string> Reserved =
    [
        "com0", "com1", "com2",
        "com3", "com4", "com5",
        "com6", "com7", "com8", "com9",
        "builtins", "collections",
        "debug", "std", "test", "bump",
        "nul", "null", "prn", "aux",
        "vin", "http", "grpc", "logger",
        "core", "kernel", "live", "docker",

        "avatars", "assets", "bookmarks",
        "checks", "conversations", "labels",
        "media", "nodes", "owners", "page",
        "registry", "seats", "shared", "tasks",
        "uploads", "account", "apps", "blog", "c",
        "contact", "contributing", "customer", "customers",
        "developer", "edu", "guides", "help", "launch", "mac",
        "mirrors", "pages", "plans", "press", "readme", "repositories",
        "resources", "security", "settings", "signup", "terms", "topic",
        "tos", "training", "users", "wiki", "windows", "advisories",
        "collections", "dashboard-feed", "hovercards", "inbox",
        "invalid-email-address", "suggestions", "suspended",
        "case-studies", "watching",
        "save-net-neutrality",
        "ghost",
        "status",
          "about",
          "account",
          "admin",
          "advisories",
          "anonymous",
          "any",
          "api",
          "apps",
          "attributes",
          "auth",
          "billing",
          "blob",
          "blog",
          "bounty",
          "branches",
          "business",
          "businesses",
          "c",
          "cache",
          "case-studies",
          "categories",
          "central",
          "certification",
          "changelog",
          "chat",
          "cla",
          "cloud",
          "codereview",
          "collection",
          "collections",
          "comments",
          "commit",
          "commits",
          "companies",
          "compare",
          "contact",
          "contributing",
          "cookbook",
          "coupons",
          "customer-stories",
          "customer",
          "customers",
          "dashboard-feed",
          "dashboard",
          "dashboards",
          "design",
          "develop",
          "developer",
          "diff",
          "discover",
          "discussions",
          "downloads",
          "downtime",
          "editor",
          "editors",
          "edu",
          "enterprise",
          "events",
          "explore",
          "featured",
          "features",
          "files",
          "fixtures",
          "forked",
          "garage",
          "ghost",
          "gist",
          "gists",
          "graphs",
          "guide",
          "guides",
          "help",
          "help-wanted",
          "home",
          "hooks",
          "hosting",
          "hovercards",
          "identity",
          "images",
          "inbox",
          "individual",
          "info",
          "integration",
          "interfaces",
          "introduction",
          "invalid-email-address",
          "investors",
          "issues",
          "jobs",
          "join",
          "journal",
          "journals",
          "lab",
          "labs",
          "languages",
          "launch",
          "layouts",
          "learn",
          "legal",
          "library",
          "linux",
          "listings",
          "lists",
          "login",
          "logos",
          "logout",
          "mac",
          "maintenance",
          "malware",
          "man",
          "marketplace",
          "mention",
          "mentioned",
          "mentioning",
          "mentions",
          "migrating",
          "milestones",
          "mine",
          "mirrors",
          "mobile",
          "navigation",
          "network",
          "new",
          "news",
          "none",
          "nonprofit",
          "nonprofits",
          "notices",
          "notifications",
          "oauth",
          "offer",
          "open-source",
          "organisations",
          "organizations",
          "orgs",
          "pages",
          "partners",
          "payments",
          "personal",
          "plans",
          "plugins",
          "popular",
          "popularity",
          "posts",
          "press",
          "pricing",
          "professional",
          "projects",
          "pulls",
          "raw",
          "readme",
          "recommendations",
          "redeem",
          "releases",
          "render",
          "reply",
          "repositories",
          "resources",
          "restore",
          "revert",
          "save-net-neutrality",
          "saved",
          "scraping",
          "search",
          "security",
          "services",
          "sessions",
          "settings",
          "shareholders",
          "shop",
          "showcases",
          "signin",
          "signup",
          "site",
          "spam",
          "sponsors",
          "ssh",
          "staff",
          "starred",
          "stars",
          "static",
          "status",
          "statuses",
          "storage",
          "store",
          "stories",
          "styleguide",
          "subscriptions",
          "suggest",
          "suggestion",
          "suggestions",
          "support",
          "suspended",
          "talks",
          "teach",
          "teacher",
          "teachers",
          "teaching",
          "team",
          "teams",
          "ten",
          "terms",
          "timeline",
          "topic",
          "topics",
          "tos",
          "tour",
          "train",
          "training",
          "translations",
          "tree",
          "trending",
          "updates",
          "username",
          "users",
          "visualization",
          "w",
          "watching",
          "wiki",
          "windows",
          "works-with",
          "www0",
          "www1",
          "www2",
          "www3",
          "www4",
          "www5",
          "www6",
          "www7",
          "www8",
          "www9"
    ];

    public static async Task ValidateExistAsync(Shard shard)
    {
        if (shard.Description?.Length > 70)
            throw new PackageValidatorException($"{nameof(Shard.Description)} is more 70 symbols.");
        if (shard.Name?.Length > 30)
            throw new PackageValidatorException($"{nameof(Shard.Name)} is more 30 symbols.");
        if (shard.Size > MaxAllowedContentForUploading)
            throw new PackageValidatorException($"Size of package is more 300 MB.");
        await using var icon = await shard.GetIconAsync();

        if (icon is null)
            throw new PackageValidatorException($"Package required icon");

        if (icon.Length > MaxAllowedIconLengthForUploading)
            throw new PackageValidatorException($"Size of icon is more 1 MB.");

        if (_censor.ContainsProfanity(shard.Description))
            throw new PackageValidatorException($"{nameof(Shard.Description)} is contained banned words.");

    }


    public static void ValidateNewPackage(Package package)
    {
        if (IsReservedName(package))
            throw new PackageValidatorException(
                $"Name '{package.Name}' has been reserved.\n " +
                $"If you want to use a reserved package name, please create an issue in " +
                $"https://github.com/vein-lang/registry");
        if (_censor.ContainsProfanity(package.Name))
            throw new PackageValidatorException($"{nameof(Shard.Name)} is contained banned words.");
    }


    public static bool IsReservedName(Package package)
        => Reserved.Any(x => package.Name.Equals(x, StringComparison.InvariantCultureIgnoreCase)) ||
           package.Name.Length < 2 ||
           package.Name.StartsWith("vein", StringComparison.InvariantCultureIgnoreCase);
}


public class PackageValidatorException : Exception
{
    public PackageValidatorException(string msg) : base(msg) { }
}
